In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [13]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
np.linspace(0, 5, 10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [15]:
# create an identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [16]:
np.random.rand(3)

array([ 0.36008392,  0.60373874,  0.21280927])

In [17]:
np.random.randn(5)

array([-0.49915138, -1.37263811, -1.50508591, -1.70000199,  0.9794377 ])

In [18]:
np.random.randn(5, 6)

array([[ 2.02870687,  1.77127042,  0.20002695,  1.12042565, -0.06456385,
        -0.08693985],
       [-1.04581497,  0.462726  ,  0.00688123,  1.13290767, -0.79071616,
         1.48815371],
       [-0.65135881, -0.19813779,  0.34004123, -0.06575869,  0.64229475,
        -0.84357246],
       [ 1.2229551 ,  0.98631546,  1.14231592, -0.89060917, -0.94892357,
         0.99576623],
       [ 0.21235233,  1.34458588,  0.70329921, -1.44889399, -0.09786969,
        -1.29045443]])

In [20]:
np.random.randint(1, 100, 10)

array([49, 82, 94,  2, 34, 40, 95, 91, 82, 48])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0, 50, 10)

In [24]:
ranarr

array([28, 33, 47, 28,  1, 31, 46, 49, 11, 40])

In [25]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.reshape(2, 5)

array([[28, 33, 47, 28,  1],
       [31, 46, 49, 11, 40]])

In [27]:
ranarr.reshape(5, 2)

array([[28, 33],
       [47, 28],
       [ 1, 31],
       [46, 49],
       [11, 40]])

In [28]:
ranarr.argmax()
# returns the index location for the max

7

In [29]:
ranarr.argmin()

4

In [33]:
arr.shape

(25,)

In [32]:
ranarr.shape

(10,)

In [34]:
arr.dtype

dtype('int64')

In [35]:
arr = np.arange(0, 11)

In [36]:
arr[8]

8

In [37]:
arr[3:4]

array([3])

In [38]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [40]:
# slice of the original array is not copied data, so if we made changes to the slice, it will also apply to the original array.
slice_of_arr = arr[0:6]

In [43]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [42]:
slice_of_arr[:] = 99

In [45]:
# to avoid memory issues of very large arrays!!!
# need to specify if you want a copy of that original array
arr_copy = arr.copy()

In [48]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [47]:
arr_copy[:] = 100

In [50]:
# indexing a matrix
arr = np.arange(5, 46, 5)

In [52]:
arr = arr.reshape(3, 3)

In [53]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr[0][0]

5

In [56]:
# recommend: comma, single bracket notation
arr[1, 2]

30

In [57]:
arr[:2, 1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [60]:
arr[:, 1:] # how to select a col in a array?????? use ":" for the row dimension.

array([[10, 15],
       [25, 30],
       [40, 45]])

In [61]:
arr = np.arange(1, 11)

In [63]:
bool_arr = arr > 5

In [64]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [65]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr > 5] # conditional selection, all happens in one step.
#just passing the bool_arr values inside the square breacket itself~

array([ 6,  7,  8,  9, 10])

In [67]:
arr_2d = np.arange(50).reshape(5, 10)

In [68]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
arr_2d[:, 0]

array([ 0, 10, 20, 30, 40])

In [70]:
arr = np.arange(11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])