Slicing a string

In [1]:
s = 'abcdefghijk'

In [2]:
s[0:]

'abcdefghijk'

In [3]:
s[:3] # up to but not including index 3

'abc'

In [4]:
s[3:6]

'def'

### list, append method, nested list

In [5]:
my_list = ['a' , 'b', 'c']

In [6]:
my_list.append('d')

In [7]:
my_list[1:3]

['b', 'c']

In [8]:
my_list[0] = 'new'

In [9]:
my_list

['new', 'b', 'c', 'd']

In [10]:
nest = [1, 2, [3, 4]]

In [11]:
nest[2][1]

4

### Dictionary, key value pairs

In [12]:
d = {'key1': 'the value', 'key2': 23}

In [13]:
d['key1']

'the value'

In [14]:
d2 = {'k1': {'innerkey': [1, 2, 3]}}

In [15]:
d2['k1']['innerkey'][1]

2

### For loop, While loop

In [16]:
seq = [1, 2, 3, 4, 5]

In [19]:
for num in seq:
    print 'hello' + str(num)

hello1
hello2
hello3
hello4
hello5


In [20]:
i = 1
while i < 5:
    print 'i is: {}'.format(i)
    i +=1

i is: 1
i is: 2
i is: 3
i is: 4


### Range

In [21]:
for x in range(0, 5):
    print x

0
1
2
3
4


In [22]:
list(range(3, 5))

[3, 4]

In [23]:
x = [1, 2, 3, 4]

In [24]:
out = []

In [25]:
for num in x:
    out.append(num ** 2)

In [26]:
out

[1, 4, 9, 16]

list comprehension

In [27]:
[num**2 for num in x]

[1, 4, 9, 16]

### Functions

In [ ]:
map() #<-- put the function to the sequence

In [28]:
def times2(num):
    return num*2

In [29]:
map(times2, x)

[2, 4, 6, 8]

In [31]:
map(lambda num: num*66, seq)

[66, 132, 198, 264, 330]

In [32]:
filter(lambda num: num %2 == 0, seq)

[2, 4]

### Methods

In [35]:
s.find('k')

10

In [36]:
tweet = "Go Sports! #Sports"

In [37]:
tweet.split("#") # <-- grab the hashtag from a tweet!

['Go Sports! ', 'Sports']

In [39]:
d.keys()

['key2', 'key1']

In [40]:
d.items()

[('key2', 23), ('key1', 'the value')]

In [41]:
d.values()

[23, 'the value']

In [44]:
my_list.pop()

'd'

In [45]:
my_list

['new', 'b', 'c']

In [46]:
'a' in x

False

In [47]:
x

[1, 2, 3, 4]

In [48]:
3 in x

True

### Tuple unpacking

In [49]:
x = [(1, 2), (3, 4), (5, 6)]


In [51]:
for (a, b) in x:
    print a

1
3
5


### Just grab the one part of the tuple!!!

### Numpy Arrays

In [52]:
import numpy as np

In [53]:
my_list

['new', 'b', 'c']

In [54]:
np.array(my_list)

array(['new', 'b', 'c'], 
      dtype='|S3')

In [55]:
my_mat = [[1, 2, 3], my_list]

In [56]:
np.array(my_mat)

array([['1', '2', '3'],
       ['new', 'b', 'c']], 
      dtype='|S21')

In [57]:
np.linspace(0, 5, 9)

array([ 0.   ,  0.625,  1.25 ,  1.875,  2.5  ,  3.125,  3.75 ,  4.375,  5.   ])

In [58]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [59]:
np.random.rand() #<-- uniform distribution

0.20257949707740708

In [60]:
np.random.rand(5, 5)

array([[ 0.34305204,  0.19924282,  0.84949736,  0.96307348,  0.23504301],
       [ 0.67289394,  0.04097826,  0.53783306,  0.62452004,  0.34508785],
       [ 0.44666481,  0.68879459,  0.27024965,  0.23598569,  0.43724184],
       [ 0.75911498,  0.87640126,  0.9334654 ,  0.50096237,  0.82612139],
       [ 0.22930223,  0.74650691,  0.93181244,  0.18219013,  0.22590179]])

In [62]:
np.random.randn(5,5) # <- standard normal distribution

array([[-1.52636742,  0.05124921, -0.19181286, -0.57671118, -0.7194188 ],
       [-1.3972353 ,  3.48877615,  1.54133779,  0.38258319,  0.6498917 ],
       [ 0.77906908,  0.21566674, -0.87843761, -0.87073442, -1.42121931],
       [ 2.06928176,  0.4949158 ,  0.4501967 ,  0.52901687, -0.16353534],
       [ 0.48269654, -1.26787567, -1.10319891,  1.93694402, -0.22113919]])

In [64]:
arr = np.random.randint(1, 100, size = 4)

In [65]:
arr.reshape(2, 2)

array([[51, 29],
       [54, 50]])

In [66]:
arr.argmax()

2

In [67]:
arr.max()

54

In [68]:
arr.dtype

dtype('int64')

In [69]:
arr = np.arange(0, 11)

In [70]:
arr[8]

8

In [71]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [72]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [73]:
slice_of_arr = arr[:6]

In [75]:
slice_of_arr[:] = 99

In [76]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_copy = arr[:6].copy()

In [80]:
arr_copy

array([99, 99, 99, 99, 99, 99])

In [81]:
arr_copy = np.arange(0, 6)

In [82]:
arr_copy

array([0, 1, 2, 3, 4, 5])

In [83]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [84]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[0][0]

5

In [87]:
arr_2d[2][1]

40

In [88]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [89]:
arr_1d = np.arange(1, 11)

In [91]:
bool_arr = arr_1d > 5

In [93]:
arr_1d[bool_arr]

array([ 6,  7,  8,  9, 10])

In [94]:
arr[arr > 5]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [95]:
arr[ arr < 11]

array([ 6,  7,  8,  9, 10])

In [96]:
arr_2d_2 = np.arange(50).reshape(10, 5)

In [97]:
arr_2d_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [98]:
arr_2d_2[2:3, 3:]

array([[13, 14]])