Slicing a string

In [2]:
s = 'abcdefghijk'

In [3]:
s[0:]

'abcdefghijk'

In [4]:
s[:3] # up to but not including index 3

'abc'

In [5]:
s[3:6]

'def'

### list, append method, nested list

In [6]:
my_list = ['a' , 'b', 'c']

In [7]:
my_list.append('d')

In [8]:
my_list[1:3]

['b', 'c']

In [9]:
my_list[0] = 'new'

In [10]:
my_list

['new', 'b', 'c', 'd']

In [11]:
nest = [1, 2, [3, 4]]

In [12]:
nest[2][1]

4

### Dictionary, key value pairs

In [13]:
d = {'key1': 'the value', 'key2': 23}

In [14]:
d['key1']

'the value'

In [15]:
d2 = {'k1': {'innerkey': [1, 2, 3]}}

In [16]:
d2['k1']['innerkey'][1]

2

### For loop, While loop

In [17]:
seq = [1, 2, 3, 4, 5]

In [18]:
for num in seq:
    print 'hello' + str(num)

hello1
hello2
hello3
hello4
hello5


In [19]:
i = 1
while i < 5:
    print 'i is: {}'.format(i)
    i +=1

i is: 1
i is: 2
i is: 3
i is: 4


### Range

In [20]:
for x in range(0, 5):
    print x

0
1
2
3
4


In [21]:
list(range(3, 5))

[3, 4]

In [22]:
x = [1, 2, 3, 4]

In [23]:
out = []

In [24]:
for num in x:
    out.append(num ** 2)

In [25]:
out

[1, 4, 9, 16]

list comprehension

In [26]:
[num**2 for num in x]

[1, 4, 9, 16]

### Functions

In [28]:
#map() #<-- put the function to the sequence

In [29]:
def times2(num):
    return num*2

In [30]:
map(times2, x)

[2, 4, 6, 8]

In [31]:
map(lambda num: num*66, seq)

[66, 132, 198, 264, 330]

In [32]:
filter(lambda num: num %2 == 0, seq)

[2, 4]

### Methods

In [33]:
s.find('k')

10

In [34]:
tweet = "Go Sports! #Sports"

In [35]:
tweet.split("#") # <-- grab the hashtag from a tweet!

['Go Sports! ', 'Sports']

In [36]:
d.keys()

['key2', 'key1']

In [37]:
d.items()

[('key2', 23), ('key1', 'the value')]

In [38]:
d.values()

[23, 'the value']

In [39]:
my_list.pop()

'd'

In [40]:
my_list

['new', 'b', 'c']

In [41]:
'a' in x

False

In [42]:
x

[1, 2, 3, 4]

In [43]:
3 in x

True

### Tuple unpacking

In [44]:
x = [(1, 2), (3, 4), (5, 6)]


In [45]:
for (a, b) in x:
    print a

1
3
5


### Just grab the one part of the tuple!!!

### Numpy Arrays

In [46]:
import numpy as np

In [47]:
my_list

['new', 'b', 'c']

In [48]:
np.array(my_list)

array(['new', 'b', 'c'], 
      dtype='|S3')

In [49]:
my_mat = [[1, 2, 3], my_list]

In [50]:
np.array(my_mat)

array([['1', '2', '3'],
       ['new', 'b', 'c']], 
      dtype='|S21')

In [51]:
np.linspace(0, 5, 9)

array([ 0.   ,  0.625,  1.25 ,  1.875,  2.5  ,  3.125,  3.75 ,  4.375,  5.   ])

In [52]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [53]:
np.random.rand() #<-- uniform distribution

0.3637232286418134

In [54]:
np.random.rand(5, 5)

array([[ 0.51080652,  0.96430331,  0.84634041,  0.19778512,  0.15979239],
       [ 0.41827508,  0.22148033,  0.70366308,  0.98612811,  0.93770194],
       [ 0.11949469,  0.69365752,  0.30573077,  0.05711672,  0.45800187],
       [ 0.60913522,  0.20564329,  0.58573229,  0.96072798,  0.90096051],
       [ 0.05668813,  0.8822117 ,  0.8905192 ,  0.20433872,  0.43662601]])

In [55]:
np.random.randn(5,5) # <- standard normal distribution

array([[-0.15961346,  0.48664266, -1.35234983,  0.39069581, -0.92700144],
       [-1.06317725, -0.71960399,  1.17494439, -0.78759076, -1.02926029],
       [-0.4993292 ,  0.19944462, -1.22760601,  0.06911876,  0.60476815],
       [ 1.27028967, -1.79970399,  0.89350343,  1.08555264, -1.3526724 ],
       [-1.53621323, -1.25792591, -1.08855519,  0.51556632, -0.33875782]])

In [56]:
arr = np.random.randint(1, 100, size = 4)

In [57]:
arr.reshape(2, 2)

array([[64,  8],
       [14,  6]])

In [58]:
arr.argmax()

0

In [59]:
arr.max()

64

In [60]:
arr.dtype

dtype('int64')

In [61]:
arr = np.arange(0, 11)

In [62]:
arr[8]

8

In [63]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [64]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [65]:
slice_of_arr = arr[:6]

In [66]:
slice_of_arr[:] = 99

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy = arr[:6].copy()

In [69]:
arr_copy

array([99, 99, 99, 99, 99, 99])

In [70]:
arr_copy = np.arange(0, 6)

In [71]:
arr_copy

array([0, 1, 2, 3, 4, 5])

In [72]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [73]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d[0][0]

5

In [75]:
arr_2d[2][1]

40

In [76]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [77]:
arr_1d = np.arange(1, 11)

In [78]:
bool_arr = arr_1d > 5

In [79]:
arr_1d[bool_arr]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr > 5]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [81]:
arr[ arr < 11]

array([ 6,  7,  8,  9, 10])

In [82]:
arr_2d_2 = np.arange(50).reshape(10, 5)

In [83]:
arr_2d_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [84]:
arr_2d_2[2:3, 3:]

array([[13, 14]])

In [85]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [86]:
np.median(arr)

99.0

In [ ]:
def middle_way(a, b):
  def is_x_middle(x, y, z):
    if (x >= y and x <=z) or (x <=y and x >= z):
      return True
    return False
    
  def get_middle(array_input):
    if is_x_middle(array_input[0], array_input[1], array_input[2]):
      return array_input[0]
    if is_x_middle(array_input[1], array_input[0], array_input[2]):
      return array_input[1]
    return array_input[2]
    
  return [get_middle(a), get_middle(b)]
  

In [87]:
def count_evens(nums):
    nums_bool = nums % 2 == 0
    return sum(nums_bool)

In [88]:
count_evens(arr)

3

In [109]:
def sum13(nums):
  if len(nums) == 0:
    return 0
  elif nums[0] == 13:
    sum_ = 0
    for i in range(1, len(nums)):
      if nums[i] == 13:
        sum_ += 0
      elif nums[i - 1] == 13:
        sum_ += 0
      else:
        sum_ += nums[i]
      #print(sum_, nums[i])
  else:
    sum_ = nums[0]
    for i in range(1, len(nums)):
      if nums[i] == 13:
        sum_ += 0
      elif nums[i - 1] == 13:
        sum_ += 0
      else:
        sum_ += nums[i]
      #print(sum_, nums[i])
  return sum_   

In [110]:
sum13([13, 8, 13, 13, 2, 2, 1, 13])

3

In [111]:
sum13([1, 2, 13, 2, 1, 13])

4

In [105]:
range(1,5)

[1, 2, 3, 4]

In [114]:
"""
Return the sum of the numbers in the array, returning 0 for an empty array. 
Except the number 13 is very unlucky, so it does not count and numbers that come immediately after a 13 
also do not count."""

def sum13(nums):
    i = 0
    sum = 0
    while i < len(nums):
        if (nums[i] == 13):
            i = i+2
        else:
            sum = sum + nums[i]
            i += 1
    return sum
    
            
    

In [115]:
sum13([1, 2, 2, 1, 13])

6

In [116]:
sum13([])

0

In [117]:
sum13([13, 1, 2, 13, 13, 2, 1, 13]) 

5

In [118]:
lst_nums = [3, 1, 2, 13, 13, 6, 2, 1, 7, 13, 10, 8, 7, 80]

In [120]:
index_seven = [i for i, num in enumerate(lst_nums) if num == 7] 

In [122]:
max(index_seven)

12

In [164]:
test_list = [1, 6, 8, 10, 20, 7, 2, 6, 2, 7, 1, 6, 99, 99, 7]

In [132]:
index_six = [i for i, num in enumerate(test_list) if num == 6]
index_seven = [i for i, num in enumerate(test_list) if num == 7] 

In [133]:
print(index_six,index_seven)

([1, 7, 11], [5, 9, 14])


In [162]:
def sum67(nums):
    sum_ = 0
    i = 0
    between_6_7 = False
    
    while i < len(nums):    
        if nums[i] == 6 and not between_6_7:
            between_6_7 = True
        elif nums[i] == 7 and between_6_7:
            between_6_7 = False
        elif not between_6_7:
            sum_ += nums[i]
        i += 1

    return sum_

In [ ]:
def sum67(nums):
    if len(nums) == 0:
        return 0
    sum_ = 0
    i = 0
    if 6 in nums and 7 in nums:
      specialMode = False
      
      while i < len(nums):
          if nums[i] == 6:
            specialMode = True
          elif nums[i] == 7 and specialMode:
            specialMode = False
          elif not specialMode:
            sum_ += nums[i]
          i=i+1
    else:
      sum_ = sum(nums)
      
    return sum_

In [163]:
sum67([1, 2, 2, 6, 99, 99, 7])

5

In [166]:
sum67(test_list)

4

In [188]:
def round_sum(a, b, c):
    def round10(num):
        num_lst = [int(d) for d in str(num)]
        if len(num_lst) == 1:
            if num < 5:
                return 0
            else:
                return 10
        elif num_lst[-1] < 5:
            return num - num_lst[-1]
        else:
            return num - num_lst[-1] + 10

    return round10(a) + round10(b) + round10(c)

In [189]:
round_sum(16, 27,18)

70

In [190]:
number_test = 16
[int(d) for d in str(number_test)]

[1, 6]

In [191]:
9%5

4

In [192]:
9/5

1

In [197]:
def no_teen_sum(a, b, c):
    def fix_teen(num):
        if num >= 13 and num <= 19:
            if num <> 15 and num <> 16:
                return 0
        else:
            return num
  
    return fix_teen(a) + fix_teen(b) + fix_teen(c)

In [198]:
no_teen_sum(2, 1, 14) 

3

In [202]:
class Foo:
  a = 5
  
fooInstance = Foo()

print(isinstance(fooInstance, Foo))
print(isinstance(fooInstance, (list, tuple)))
print(isinstance(fooInstance, (list, tuple, Foo)))

True
False
True


In [203]:
"""
Write a function that returns the elements on odd positions (0
based) in a list
"""
def solution(input):
    output = []
    for i in range(len(input)):
        if i % 2 != 0:
            output.append(input[i])
    return output

In [204]:
solution([0,1,2,3,4,5])

[1, 3, 5]

In [205]:
"""
Write a function that returns the cumulative sum of elements in a
list
"""
def solution(input):
    output = []
    sum_ = 0
    for i in range(len(input)):
        sum_ += input[i]
        output.append(sum_)
    return output

In [207]:
solution([1,20,1]) 

[1, 21, 22]

In [208]:
"""
Write a function that takes a number and returns a list of its
digits
"""
def solution(input):
    output = [int(d) for d in str(input)]
    return output

In [209]:
solution(123)

[1, 2, 3]